// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"dialogue/internal/biz"
	"dialogue/internal/data"
)

// Injectors from wire.go:

func InitDialogueService() (*DialogueService, func(), error) {
	cacher := data.NewCache()
	dialogueManage := biz.NewDialogueManage(cacher)
	dialogueService, cleanup, err := NewDialogueService(dialogueManage)
	if err != nil {
		return nil, nil, err
	}
	return dialogueService, func() {
		cleanup()
	}, nil
}
